### ISSUE TITLE
CI failure due to ssh key issue

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/filecoin-ffi#441] opened 2023-12-08 19:35 UTC
CI is showing this error:

```
Using SSH Config Dir '/home/circleci/.ssh'
git version 2.41.0
Cloning git repository
Cloning into '.'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

exit status 128
```

I don't have access to check/update ssh keys it seems, so flagging that someone with access should resolve this.

**Comment by vmx** [comment] 2023-12-11 11:57
I think the issue is fixed now.

**Closed** 2023-12-11 11:57 UTC
